# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .training import Training
from .version import VERSION

from models.project_settings import ProjectSettings
from models.project_model import ProjectModel
from models.project_update_model import ProjectUpdateModel

training = Training()

__all__ = ['Training']

__version__ = VERSION

