# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .image_label_result_model import ImageLabelResultModel
from .image_bounding_box import ImageBoundingBox
from .image_label_model import ImageLabelModel
from .image_model import ImageModel
from .image_url_create_batch import ImageUrlCreateBatch
from .image_upload_result_model import ImageUploadResultModel
from .image_upload_summary import ImageUploadSummary
from .image_url_batch import ImageUrlBatch
from .image_label_create_model import ImageLabelCreateModel
from .image_region import ImageRegion
from .image_result_model import ImageResultModel
from .image_model_obsolete import ImageModelObsolete
from .project_settings import ProjectSettings
from .project_model import ProjectModel
from .project_update_model import ProjectUpdateModel
from .image_class_model import ImageClassModel
from .iteration_result_model import IterationResultModel
from .iteration_model import IterationModel
from .image_class_evaluation import ImageClassEvaluation
from .user_image_evaluation import UserImageEvaluation
from .user_image_results import UserImageResults

__all__ = [
    'ImageLabelResultModel',
    'ImageBoundingBox',
    'ImageLabelModel',
    'ImageModel',
    'ImageUrlCreateBatch',
    'ImageUploadResultModel',
    'ImageUploadSummary',
    'ImageUrlBatch',
    'ImageLabelCreateModel',
    'ImageRegion',
    'ImageResultModel',
    'ImageModelObsolete',
    'ProjectSettings',
    'ProjectModel',
    'ProjectUpdateModel',
    'ImageClassModel',
    'IterationResultModel',
    'IterationModel',
    'ImageClassEvaluation',
    'UserImageEvaluation',
    'UserImageResults',
]
