# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ImageLabelModel(Model):
    """ImageLabelModel.

    :param label_id:
    :type label_id: str
    :param created_at:
    :type created_at: datetime
    :param performance:
    :type performance: :class:`ImageLabelResultModel
     <training.models.ImageLabelResultModel>`
    :param tag_id:
    :type tag_id: str
    :param region:
    :type region: :class:`ImageBoundingBox <training.models.ImageBoundingBox>`
    """

    _attribute_map = {
        'label_id': {'key': 'LabelId', 'type': 'str'},
        'created_at': {'key': 'CreatedAt', 'type': 'iso-8601'},
        'performance': {'key': 'Performance', 'type': 'ImageLabelResultModel'},
        'tag_id': {'key': 'TagId', 'type': 'str'},
        'region': {'key': 'Region', 'type': 'ImageBoundingBox'},
    }

    def __init__(self, label_id=None, created_at=None, performance=None, tag_id=None, region=None):
        self.label_id = label_id
        self.created_at = created_at
        self.performance = performance
        self.tag_id = tag_id
        self.region = region