# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ImageBoundingBox(Model):
    """Bounding box that associates Tags with Images.

    :param top: Coordinate of the top boundary
    :type top: float
    :param left: Coordinate of the Left boundary
    :type left: float
    :param width: Width
    :type width: float
    :param height: Height
    :type height: float
    """

    _attribute_map = {
        'top': {'key': 'Top', 'type': 'float'},
        'left': {'key': 'Left', 'type': 'float'},
        'width': {'key': 'Width', 'type': 'float'},
        'height': {'key': 'Height', 'type': 'float'},
    }

    def __init__(self, top=None, left=None, width=None, height=None):
        self.top = top
        self.left = left
        self.width = width
        self.height = height
