# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ImageClassModel(Model):
    """ImageCategory model to send over JSON.

    :param id: Gets or sets the primary key database property
    :type id: str
    :param name: Gets or sets the name database property
    :type name: str
    :param description: Gets or sets the description database property
    :type description: str
    :param image_count: Gets or sets the number of images in this category
    :type image_count: int
    :param thumbnail: Gets or sets the thumbnail id to represent the category
    :type thumbnail: str
    """

    _attribute_map = {
        'id': {'key': 'Id', 'type': 'str'},
        'name': {'key': 'Name', 'type': 'str'},
        'description': {'key': 'Description', 'type': 'str'},
        'image_count': {'key': 'ImageCount', 'type': 'int'},
        'thumbnail': {'key': 'Thumbnail', 'type': 'str'},
    }

    def __init__(self, id=None, name=None, description=None, image_count=None, thumbnail=None):
        self.id = id
        self.name = name
        self.description = description
        self.image_count = image_count
        self.thumbnail = thumbnail

    def get_classname(self):
        return self.name

    def get_classid(self):
        return self.id




