# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ImageUrlCreateBatch(Model):
    """ImageUrlCreateBatch.

    :param tag_ids:
    :type tag_ids: list of str
    :param urls:
    :type urls: list of str
    """

    _attribute_map = {
        'tag_ids': {'key': 'TagIds', 'type': '[str]'},
        'urls': {'key': 'Urls', 'type': '[str]'},
    }

    def __init__(self, tag_ids=None, urls=None):
        self.tag_ids = tag_ids
        self.urls = urls
