# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IterationModel(Model):
    """Iteration model to be sent over JSON.

    :param last_modified_time_stamp: Gets or sets the last modifed time stamp
    :type last_modified_time_stamp: datetime
    :param created_time_stamp: Gets or sets the created time stamp
    :type created_time_stamp: datetime
    :param id: Gets or sets the primary database id of the iteration
    :type id: str
    :param name: Gets or sets the name database property
    :type name: str
    :param status: Gets or sets the status database property
    :type status: str
    :param configuration: Gets or sets the configuration database property
    :type configuration: str
    :param performance_results: Gets or sets the performance results
    :type performance_results: :class:`IterationResultModel
     <training.models.IterationResultModel>`
    :param published: Gets or sets a value indicating whether the iteration is
     published databased property
    :type published: bool
    :param evaluation_url: Gets or sets the evaluation endpoint for this
     iteration
    :type evaluation_url: str
    """

    _attribute_map = {
        'last_modified_time_stamp': {'key': 'LastModifiedTimeStamp', 'type': 'iso-8601'},
        'created_time_stamp': {'key': 'CreatedTimeStamp', 'type': 'iso-8601'},
        'id': {'key': 'Id', 'type': 'str'},
        'name': {'key': 'Name', 'type': 'str'},
        'status': {'key': 'Status', 'type': 'str'},
        'configuration': {'key': 'Configuration', 'type': 'str'},
        'performance_results': {'key': 'PerformanceResults', 'type': 'IterationResultModel'},
        'published': {'key': 'Published', 'type': 'bool'},
        'evaluation_url': {'key': 'EvaluationUrl', 'type': 'str'},
    }

    def __init__(self, last_modified_time_stamp=None, created_time_stamp=None, id=None, name=None, status=None, configuration=None, performance_results=None, published=None, evaluation_url=None):
        self.last_modified_time_stamp = last_modified_time_stamp
        self.created_time_stamp = created_time_stamp
        self.id = id
        self.name = name
        self.status = status
        self.configuration = configuration
        self.performance_results = performance_results
        self.published = published
        self.evaluation_url = evaluation_url
