# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ProjectSettings(Model):
    """ProjectSettings.

    :param featurizers:
    :type featurizers: list of str
    :param should_predict_single_label_per_image:
    :type should_predict_single_label_per_image: bool
    """

    _attribute_map = {
        'featurizers': {'key': 'Featurizers', 'type': '[str]'},
        'should_predict_single_label_per_image': {'key': 'ShouldPredictSingleLabelPerImage', 'type': 'bool'},
    }

    def __init__(self, featurizers=None, should_predict_single_label_per_image=None):
        self.featurizers = featurizers
        self.should_predict_single_label_per_image = should_predict_single_label_per_image
